# deploy/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: grafana
    releaseName: grafana-base
    repo: https://grafana.github.io/helm-charts
    version: 8.5.x
