# Production-ready settings
replicas: 1
persistence:
  enabled: true
  size: 10Gi
ingress:
  enabled: false
  hosts:
    - grafana.example.com

# Tell Helm NOT to create or use a secret for the admin password

#      fullnameOverride: lhw-data-analysis-grafana
admin:
  existingSecret: "manual-vault-injection"

ldap:
  enabled: true
  existingSecret: "manual-vault-injection"
  allowSignUp: true
  config_file: "/vault/secrets/ldap.toml"
